table DimMercados
	lineageTag: 765852c9-dd81-460b-ad6a-b57fab9afbc7

	column Mercado
		dataType: string
		lineageTag: 7e6c567a-9f31-4a5b-b746-484d0addac92
		summarizeBy: none
		sourceColumn: Mercado

		annotation SummarizationSetBy = Automatic

	column Id_Mercado
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: d3ae8768-13fd-46f5-af54-ae58140ec00f
		summarizeBy: none
		sourceColumn: Id_Mercado

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimMercados = m
		mode: import
		queryGroup: 'Dimensiones Sintéticas'
		source =
				let
				    // Origen de datos, referencia a la tabla de origen
				    Origen = TransaccionesTransaccional_agrupado,
				
				    // Seleccionar solo la columna "mercado"
				    Columnas_seleccionadas = Table.SelectColumns(
				        Origen,
				        {"mercado"}
				    ),
				
				    // Quitar duplicados
				    Duplicados_quitados = Table.Distinct(Columnas_seleccionadas),
				
				    // Agregar índice que servirá como Id_Mercado
				    Indice_agregado = Table.AddIndexColumn(
				        Duplicados_quitados,
				        "Id_Mercado",
				        1,
				        1,
				        Int64.Type
				    ),
				
				    // Renombrar columna
				    Columnas_renombradas = Table.RenameColumns(
				        Indice_agregado,
				        {{"mercado", "Mercado"}}
				    )
				in
				    Columnas_renombradas

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

