table DimTipoAplicacion
	lineageTag: 8b445670-1b54-4849-9b09-a34a1c89d524

	column 'Tipo Aplicacion'
		dataType: string
		lineageTag: 2976bfea-35d0-4ff0-887a-2fd9e5e9247c
		summarizeBy: none
		sourceColumn: Tipo Aplicacion

		annotation SummarizationSetBy = Automatic

	column Id_TipoApp
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5198cdd0-f73c-4100-8546-e2bafe33b0d6
		summarizeBy: none
		sourceColumn: Id_TipoApp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition DimTipoAplicacion = m
		mode: import
		queryGroup: 'Dimensiones Sintéticas'
		source =
				let
				    // Origen de datos, referencia a la tabla de origen
				    Origen = TransaccionesTransaccional_agrupado,
				
				    // Seleccionar únicamente la columna que nos interesa
				    Columnas_seleccionadas = Table.SelectColumns(
				        Origen,
				        {"tipo_aplicacion"}
				    ),
				
				    // Quitar duplicados para tener solo valores únicos
				    Duplicados_quitados = Table.Distinct(Columnas_seleccionadas),
				
				    // Agregar columna índice que servirá como Id_TipoApp
				    Indice_agregado = Table.AddIndexColumn(
				        Duplicados_quitados,
				        "Id_TipoApp",
				        1,
				        1,
				        Int64.Type
				    ),
				
				    // Renombrar la columna original para dejarla con nombre limpio
				    Columnas_renombradas = Table.RenameColumns(
				        Indice_agregado,
				        {{"tipo_aplicacion", "Tipo Aplicacion"}}
				    )
				in
				    Columnas_renombradas

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

