/// Tabla que contiene todas las Medidas DAX del modelo.
table Medidas
	lineageTag: cf1c3928-f1f1-486f-94dc-c5c91d3786b0

	/// Suma total de transacciones reales distribuidas por canal desde el transaccional. Representa las transacciones efectivamente completadas y registradas en el sistema de backend.
	measure 'Transacciones Real' = ```
							
							ROUND(
								SUM(FactTransacciones[transacciones_reales_distribuidas]),
								0
							)
			```
		formatString: #,0
		displayFolder: Transacciones
		lineageTag: 59a26060-b31c-4325-991d-ea9d10d1dda7

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Total de transacciones registradas por Google Analytics, agregadas por fecha, mercado y tipo de aplicación. Se utiliza para análisis comparativo contra transacciones reales del transaccional.
	measure 'Transacciones Google' = ```
							
							VAR _TransGA = 
								SUMMARIZE(
									FactTransacciones,
									FactTransacciones[fecha],
									FactTransacciones[Id_Mercado],
									FactTransacciones[Id_TipoApp],
									"Numero transacciones",
									SUM(FactTransacciones[transacciones_ga])
								)
							
							RETURN
								SUMX(
									_TransGA,
									[Numero transacciones]
								)
			```
		formatString: #,0
		displayFolder: Transacciones
		lineageTag: d94b08cb-e082-453a-adef-1f3e48607dda

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Diferencia en puntos porcentuales entre el ratio de conversión de Google y el ratio real. Valores positivos indican sobreestimación del tracking de GA respecto a ventas confirmadas.
	measure 'Diferencia Absoluta Conversion Real vs Google' = ```
			
							[Ratio Conversion Real] - [Ratio Conversion Google]
			```
		formatString: 0.00
		displayFolder: Ratios
		lineageTag: 03ddff21-48b3-46cd-aee9-ebfdeb8722f8

	/// Ratio de conversión calculado con transacciones reales del transaccional. Representa el porcentaje real de sesiones que resultan en ventas confirmadas en el backend.
	measure 'Ratio Conversion Real' = ```
			
			                        DIVIDE(
			                            [Transacciones Real],
			                            [Sesiones],
			                            0
			                        )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Ratios
		lineageTag: 07bf222b-edab-4f4d-bc24-72681c78cd8d

	/// Suma total de sesiones registradas en Google Analytics. Representa el volumen de tráfico único en el sitio web o aplicación.
	measure Sesiones = ```
							
							SUM(FactTransacciones[sesiones_ga])
			```
		formatString: #,0
		displayFolder: Transacciones
		lineageTag: 418fd39b-08f6-4f84-9a43-f5f13b08a6de

	/// Ratio de conversión calculado a partir de datos de Google Analytics. Indica el porcentaje de sesiones que resultan en transacciones según el tracking del frontend.
	measure 'Ratio Conversion Google' = ```
			
			                            DIVIDE(
			                                [Transacciones Google],
			                                [Sesiones],
			                                0
			                            )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Ratios
		lineageTag: 1ad4df52-4b77-44fe-a476-ec9e4b40ecb7

	/// Transacciones reales de la misma semana anterior. Se utiliza como base de comparación para análisis Week-over-Week.
	measure 'Transacciones Real WoW' = ```
							
							CALCULATE(
								[Transacciones Real],
								DATEADD(DimCalendario[Fecha], -7, DAY)
							)
			```
		formatString: 0.00
		displayFolder: Transacciones
		lineageTag: 942a56ef-de7d-4c24-8c3b-183123d01f36

	/// Transacciones de Google Analytics de la misma semana anterior. Se utiliza como base de comparación para análisis Week-over-Week.
	measure 'Transacciones Google WoW' = ```
							
							CALCULATE(
								[Transacciones Google],
								DATEADD(DimCalendario[Fecha], -7, DAY)
							)
			```
		formatString: 0
		displayFolder: Transacciones
		lineageTag: 7d806349-c1ab-452a-91b9-b50df6d6025b

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Transacciones de Google Analytics del mismo período del mes anterior. Se utiliza como base de comparación para análisis Month-over-Month.
	measure 'Transacciones Google MoM' = ```
							
							CALCULATE(
								[Transacciones Google],
								DATEADD(DimCalendario[Fecha], -1, MONTH)
							)
			```
		formatString: 0
		displayFolder: Transacciones
		lineageTag: de890036-d2ca-460a-98ba-517fc0488d5c

		annotation PBI_FormatHint = {"isDecimal":true}

	/// Transacciones reales del mismo período del mes anterior. Se utiliza como base de comparación para análisis Month-over-Month.
	measure 'Transacciones Real MoM' = ```
							
							CALCULATE(
								[Transacciones Real],
								DATEADD(DimCalendario[Fecha], -1, MONTH)
							)
			```
		formatString: 0.00
		displayFolder: Transacciones
		lineageTag: 7cd2d7b5-1264-4071-a3f2-18675764717c

	/// Diferencia absoluta entre transacciones reales del período actual y de la semana anterior. Valores positivos indican crecimiento semanal.
	measure 'Variacion Transacciones Real WoW' = ```
			
							[Transacciones Real] - [Transacciones Real WoW]
			```
		displayFolder: Transacciones
		lineageTag: 2053d0f3-e321-4b69-a13c-53191d5239ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Variación porcentual de transacciones reales respecto a la semana anterior. Indica tasa de crecimiento o decrecimiento semanal de ventas confirmadas.
	measure '% Variacion Transacciones Real WoW' = ```
							
							DIVIDE(
								[Variacion Transacciones Real WoW],
								[Transacciones Real WoW],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Transacciones
		lineageTag: 9e6f140c-979e-4054-acc3-9156944f716f

	/// Variación porcentual de la cesta media respecto a la semana anterior. Indica tasa de crecimiento o decrecimiento semanal del ticket promedio.
	measure '% Variacion Cesta WoW' = ```
							
							DIVIDE(
								[Variacion Cesta WoW],
								[Cesta Media WoW],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Cesta
		lineageTag: f8db81a7-2f96-43ea-935a-9b027d88b5a9

	/// Valor promedio de compra por transacción, calculado como Revenue Total dividido entre Transacciones Reales. Indica el ticket promedio de cada venta confirmada.
	measure 'Cesta Media' = ```
			
							VAR _TotalTransacciones = [Transacciones Real]
							VAR _Revenue = [Revenue Total]
							RETURN
								DIVIDE(_Revenue, _TotalTransacciones, 0)
			```
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: Cesta
		lineageTag: 6dceea30-5d28-48e9-97ed-400d58421e3a

	/// Cesta media del mismo período del mes anterior. Base de comparación para análisis Month-over-Month del valor promedio de compra.
	measure 'Cesta Media MoM' = ```
							
							CALCULATE(
								[Cesta Media],
								DATEADD(DimCalendario[Fecha], -1, MONTH)
							)
			```
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: Cesta
		lineageTag: aa44da89-4aca-4f2e-a2e6-7cb08db5a2c7

	/// Cesta media de la misma semana anterior. Base de comparación para análisis Week-over-Week del valor promedio de compra.
	measure 'Cesta Media WoW' = ```
							
							CALCULATE(
								[Cesta Media],
								DATEADD(DimCalendario[Fecha], -7, DAY)
							)
			```
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: Cesta
		lineageTag: e88b538a-4b50-46de-ae4c-17910e7da855

	/// Diferencia absoluta en euros entre la cesta media actual y de la semana anterior. Valores positivos indican incremento semanal en el ticket promedio.
	measure 'Variacion Cesta WoW' = ```
							
							[Cesta Media] - [Cesta Media WoW]
			```
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		displayFolder: Cesta
		lineageTag: 3cc23e1c-71cd-4816-946f-54a11130566d

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	/// Variación porcentual del revenue respecto al mes anterior. Indica tasa de crecimiento o decrecimiento mensual de ingresos.
	measure '% Variacion Revenue MoM' = ```
							
							DIVIDE(
								[Variacion Revenue MoM],
								[Revenue MoM],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Revenue
		lineageTag: 5d1ff881-4ae9-4d97-9e46-d4f155959712

	/// Variación porcentual del revenue respecto a la semana anterior. Indica tasa de crecimiento o decrecimiento semanal de ingresos.
	measure '% Variacion Revenue WoW' = ```
							
							DIVIDE([Variacion Revenue WoW], [Revenue WoW], 0)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Revenue
		lineageTag: 5ded3b91-85f6-4fcf-ae3e-94a7b307abd0

	/// Revenue total del mismo período del mes anterior. Base de comparación para análisis Month-over-Month de ingresos.
	measure 'Revenue MoM' = ```
							
							CALCULATE(
								[Revenue Total],
								DATEADD(DimCalendario[Fecha], -1, MONTH)
							)
			```
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: Revenue
		lineageTag: a9fd6164-fdcb-4fa3-b857-b93f181044ed

	/// Suma total del revenue distribuido por canal según la metodología de distribución por pesos de conversión. Representa los ingresos totales confirmados del período.
	measure 'Revenue Total' = ```
							
							SUM(FactTransacciones[revenue_distribuido])
			```
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: Revenue
		lineageTag: 8b8d2cad-9f39-473b-aea2-237ec633b538

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Revenue total de la misma semana anterior. Base de comparación para análisis Week-over-Week de ingresos.
	measure 'Revenue WoW' = ```
							
							CALCULATE(
								[Revenue Total],
								DATEADD(DimCalendario[Fecha], -7, DAY)
							)
			```
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		displayFolder: Revenue
		lineageTag: e0142d76-eec8-4675-87ee-09c6f36dcc6c

	/// Diferencia absoluta en euros entre el revenue actual y del mes anterior. Valores positivos indican crecimiento mensual de ingresos.
	measure 'Variacion Revenue MoM' = ```
							
							[Revenue Total] - [Revenue MoM]
			```
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		displayFolder: Revenue
		lineageTag: 74af6511-904a-421c-b26c-99817cd25142

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	/// Variación porcentual de la cesta media respecto al mes anterior. Indica tasa de crecimiento o decrecimiento mensual del ticket promedio.
	measure '% Variacion Cesta MoM' = ```
							
							DIVIDE(
								[Variacion Cesta MoM],
								[Cesta Media MoM],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Cesta
		lineageTag: a4567cee-0961-459e-a2f5-e0db39a5eb48

	/// Diferencia absoluta en euros entre la cesta media actual y del mes anterior. Valores positivos indican incremento en el ticket promedio.
	measure 'Variacion Cesta MoM' = ```
							
							[Cesta Media] - [Cesta Media MoM]
			```
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		displayFolder: Cesta
		lineageTag: 36d92c25-1924-4d38-9e02-a35b1c56cb74

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	/// Diferencia absoluta en euros entre el revenue actual y de la semana anterior. Valores positivos indican crecimiento semanal de ingresos.
	measure 'Variacion Revenue WoW' = ```
							
							[Revenue Total] - [Revenue WoW]
			```
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		displayFolder: Revenue
		lineageTag: 7922687c-012e-4620-b178-b42a24f4091d

		annotation PBI_FormatHint = {"currencyCulture":"es-AR"}

	/// Variación porcentual de transacciones reales respecto al mes anterior. Indica tasa de crecimiento o decrecimiento mensual de ventas confirmadas.
	measure '% Variacion Transacciones Real MoM' = ```
							
							DIVIDE(
								[Variacion Transacciones Real MoM],
								[Transacciones Real MoM],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Transacciones
		lineageTag: 1c00da70-3569-45bf-a82b-b8098edfecd7

	/// Diferencia absoluta entre transacciones reales del período actual y del mes anterior. Valores positivos indican crecimiento mensual.
	measure 'Variacion Transacciones Real MoM' = ```
							
							[Transacciones Real] - [Transacciones Real MoM]
			```
		displayFolder: Transacciones
		lineageTag: 31076f99-f92c-4155-ab09-3a1c759c43fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Variación porcentual de transacciones de Google respecto a la semana anterior. Indica tasa de crecimiento o decrecimiento semanal del tracking de GA.
	measure '% Variacion Transacciones Google WoW' = ```
							
							DIVIDE(
								[Variacion Transacciones Google WoW],
								[Transacciones Google WoW],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Transacciones
		lineageTag: f7ef54a1-8230-4f4a-beb0-475aef747b2a

	/// Variación porcentual de transacciones de Google respecto al mes anterior. Indica tasa de crecimiento o decrecimiento mensual del tracking de GA.
	measure '% Variacion Transacciones Google MoM' = ```
							
							DIVIDE(
								[Variacion Transacciones Google MoM],
								[Transacciones Google MoM],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Transacciones
		lineageTag: 635d2199-3a84-4d34-a01a-96016a66449e

	/// Diferencia absoluta entre transacciones de Google del período actual y de la semana anterior. Valores positivos indican crecimiento semanal.
	measure 'Variacion Transacciones Google WoW' = ```
							
							[Transacciones Google] - [Transacciones Google WoW]
			```
		formatString: 0
		displayFolder: Transacciones
		lineageTag: e37d39b8-37f6-47a9-9746-e59220f52265

	/// Diferencia absoluta entre transacciones de Google del período actual y del mes anterior. Valores positivos indican crecimiento mensual.
	measure 'Variacion Transacciones Google MoM' = ```
							
							[Transacciones Google] - [Transacciones Google MoM]
			```
		formatString: 0
		displayFolder: Transacciones
		lineageTag: a59e340e-9dd4-4c71-97e8-d738ba2870b3

	/// Variación porcentual del ratio de conversión de Google respecto al ratio real. Indica el porcentaje de discrepancia entre el tracking y las ventas confirmadas.
	measure '% Variacion Ratio Conversion Google vs Real' = ```
			
							DIVIDE(
								[Diferencia Absoluta Conversion Real vs Google],
								[Ratio Conversion Real],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Ratios
		lineageTag: d3086295-2b64-49ed-9eb7-8192615f2a1f

	/// Sesiones del mismo período del mes anterior. Se utiliza como base de comparación para análisis Month-over-Month de tráfico.
	measure 'Sesiones MoM' = ```
							
							CALCULATE(
								[Sesiones],
								DATEADD(DimCalendario[Fecha], -1, MONTH)
							)
			```
		formatString: 0
		displayFolder: Transacciones
		lineageTag: ddf52f94-465b-4add-89a1-f57e795f7084

	/// Sesiones de la misma semana anterior. Se utiliza como base de comparación para análisis Week-over-Week de tráfico.
	measure 'Sesiones WoW' = ```
							
							CALCULATE(
								[Sesiones],
								DATEADD(DimCalendario[Fecha], -7, DAY)
							)
			```
		formatString: 0
		displayFolder: Transacciones
		lineageTag: 1f3d421b-a4ef-4034-9ff0-dd6e09b96cc5

	/// Diferencia absoluta entre sesiones del período actual y de la semana anterior. Valores positivos indican crecimiento de tráfico semanal.
	measure 'Variacion Sesiones WoW' = ```
							
							[Sesiones] - [Sesiones WoW]
			```
		displayFolder: Transacciones
		lineageTag: 09494d4e-9835-42a7-b977-175161eeaabc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Diferencia absoluta entre sesiones del período actual y del mes anterior. Valores positivos indican crecimiento de tráfico mensual.
	measure 'Variacion Sesiones MoM' = ```
							
							[Sesiones] - [Sesiones MoM]
			```
		formatString: 0
		displayFolder: Transacciones
		lineageTag: 38155827-fdef-4f67-8360-e4791e5c3684

	/// Variación porcentual de sesiones respecto al mes anterior. Indica tasa de crecimiento o decrecimiento mensual del tráfico web.
	measure '% Variacion Sesiones MoM' = ```
							
							DIVIDE(
								[Variacion Sesiones MoM],
								[Sesiones MoM],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Transacciones
		lineageTag: 730ff48f-89e4-4141-b58b-5c8df0920706

	/// Variación porcentual de sesiones respecto a la semana anterior. Indica tasa de crecimiento o decrecimiento semanal del tráfico web.
	measure '% Variacion Sesiones WoW' = ```
							
							DIVIDE(
								[Variacion Sesiones WoW],
								[Sesiones WoW],
								0
							)
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Transacciones
		lineageTag: 37412622-692d-44bb-86fa-605539459a68

	column Column
		isHidden
		formatString: 0
		lineageTag: c93650ba-8d2d-45d4-931f-92cc9e2d0b5a
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Medidas = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = da77f8fb66684122b835f1c3a34c6d05

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

