createOrReplace

	table DimCalendario
		lineageTag: 336a76d2-fc97-4f23-a0e8-09b6a1dd3959
		dataCategory: Time

		column Fecha
			dataType: dateTime
			isKey
			formatString: Long Date
			lineageTag: 067af78c-d1f5-41ba-9008-d91e40af7432
			summarizeBy: none
			sourceColumn: Fecha

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		column Año
			dataType: int64
			formatString: 0
			lineageTag: 1634c7ee-f21c-40de-a6c2-5200aa4422ce
			summarizeBy: none
			sourceColumn: Año

			annotation SummarizationSetBy = Automatic

		column 'Mes Nro'
			dataType: int64
			formatString: 0
			lineageTag: df264155-9f1e-462a-8c69-d5688ebba718
			summarizeBy: none
			sourceColumn: Mes Nro

			annotation SummarizationSetBy = Automatic

		column Mes
			dataType: string
			lineageTag: 89d64ed3-9b98-4f94-9405-c451c46ecbc6
			summarizeBy: none
			sourceColumn: Mes

			annotation SummarizationSetBy = Automatic

		column Trimestre
			dataType: string
			lineageTag: ba71f6e6-fccb-4c78-9912-ae572b9c1413
			summarizeBy: none
			sourceColumn: Trimestre

			annotation SummarizationSetBy = Automatic

		column Día
			dataType: string
			lineageTag: e70927f6-0efa-4172-929b-b383f390ce3b
			summarizeBy: none
			sourceColumn: Día

			annotation SummarizationSetBy = Automatic

		column Mes-Año
			dataType: string
			lineageTag: d2112e54-6a47-4c33-956d-4a51b8274048
			summarizeBy: none
			sourceColumn: Mes-Año

			annotation SummarizationSetBy = Automatic

		column 'Semana del año'
			dataType: int64
			formatString: 0
			lineageTag: 5b9a6d25-6515-4a17-a579-11d5ce1bf42d
			summarizeBy: none
			sourceColumn: Semana del año

			annotation SummarizationSetBy = Automatic

		partition DimCalendario = m
			mode: import
			queryGroup: 'Dimensiones Sintéticas'
			source = ```
					let
					    // Usamos los valores de las consultas FechaMin y FechaMax creadas antes
					    fechas = FechasMinMax,
					    fecha_inicio = fechas[FechaMin],
					    fecha_fin = fechas[FechaMax],
					    
					    // Calculamos el número de días entre ambas fechas
					    numero_dias = Duration.Days(Duration.From(fecha_fin - fecha_inicio)) + 1,
					    
					    // Generamos la lista de fechas
					    lista_fechas = List.Dates(fecha_inicio, numero_dias, #duration(1, 0, 0, 0)),
					    
					    // Convertimos la lista en tabla
					    tabla_fechas = Table.FromList(lista_fechas, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
					    renombrar_columna_fecha = Table.RenameColumns(tabla_fechas, {{"Column1", "Fecha"}}),
					    cambiar_tipo_fecha = Table.TransformColumnTypes(renombrar_columna_fecha, {{"Fecha", type date}}),
					    
					    // Agregamos columnas útiles
					    agregar_columna_ano = Table.AddColumn(cambiar_tipo_fecha, "Año", each Date.Year([Fecha]), Int64.Type),
					    agregar_columna_mes_nro = Table.AddColumn(agregar_columna_ano, "Mes Nro", each Date.Month([Fecha]), Int64.Type),
					    agregar_columna_mes_nombre = Table.AddColumn(agregar_columna_mes_nro, "Mes", each Text.Proper(Date.MonthName([Fecha])), type text),
					    agregar_columna_trimestre = Table.AddColumn(agregar_columna_mes_nombre, "Trimestre", each "T" & Text.From(Date.QuarterOfYear([Fecha])), type text),
					    agregar_columna_dia_semana = Table.AddColumn(agregar_columna_trimestre, "Día", each Text.Proper(Date.DayOfWeekName([Fecha])), type text),
					    agregar_columna_mes_ano = Table.AddColumn(agregar_columna_dia_semana, "Mes-Año", each Text.Start([Mes], 3) & "-" & Text.End(Text.From([Año]), 2), type text),
					    agregar_columna_semana_ano = Table.AddColumn(agregar_columna_mes_ano, "Semana del año", each Date.WeekOfYear([Fecha]), Int64.Type)
					in
					    agregar_columna_semana_ano
					```

		annotation PBI_NavigationStepName = Navegación

		annotation PBI_ResultType = Table

